### ISSUE TITLE
A simple example of using this service with jquery

### ISSUE THREAD

**Issue by papakonstantinouko** [pootzko/GoogleMaps.Net.Clustering#1]
Hello, if you can provide a simple example of using this clustering service with a jquery call that gets data from a database, it would be very useful.

**Comment by tihomir-kit** [comment]
Sorry @papakonstantinouko I don't have the time for that, and it's all pretty basic anyway.. This library aims to be DB/client-side agnostic. So whatever you might be using (Entity Framework, LLBLGen, jQuery, AngularJS or something completely different), you need to know your tools. This library provides you with means to cluster the data and how you use it after that is kind of up to you.

Fetch the data from the DB, then feed your objects into the clustering lib, and return the results from a WebAPI endpoint. Query that WebAPI endpoint using jQuery ajax function and then use the data from the `.done()` callback to populate the [google maps](https://developers.google.com/maps/documentation/javascript/).
