### ISSUE TITLE
Nuget package does not support .NetStandard 2.0

### ISSUE THREAD

**Issue by JKennedy24** [pootzko/GoogleMaps.Net.Clustering#3]
Adding the nuget to my .Net Standard 2.0 project does not work

I think this is a nuget packaging issue and could be fairly straight forward

**Comment by JKennedy24** [comment]
Closing as I don't think this library is supported anymore

**Comment by tihomir-kit** [comment]
Hi, sorry for not replying. Yes, I don't really need this library any more, if someone is willing to add support to .net standard, I'll deploy the new nuget. But I don't really have the time to convert it myself. 

Cheers
